version: '3'
services:
  app:
    build:
      context: ./docker/app
    restart: always
    volumes:
      - ./web:/var/www/html
 
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ../web:/srv/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  mysqldb:
     image: mysql:${MYSQL_VERSION}
     container_name: ${MYSQL_HOST}
     restart: always
     env_file:
         - ".env"
     environment:
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     ports:
          - "33061:3306"
     volumes:
         - "./data/db_mysql_solearn/mysql:/var/lib/minesql"


  myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_dev
        ports:
            - "8091:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
